#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#

if [ -r "`dirname "$0"`/git.conf" ]; then
  . "`dirname "$0"`/git.conf"
elif [ -r "`dirname "$0"`/../git.conf" ]; then
  . "`dirname "$0"`/../git.conf"
else
  exit 1
fi

MESSAGE=$(_zenity_entry_text "Enter log message :")
if [ "$?" -eq 0 ]; then
  $GIT $GIT_OPTS commit -a -m "$MESSAGE" 1>> "$OUTPUT" 2>> "$OUTPUT"
  _zenity_info "$?" "Successfully commited" "Unknown error (more information can be found at ~/.xsession-errors)"
fi

