#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#
# http://marius.scurtescu.com/?p=102
# http://gnomefiles.org/app.php?soft_id=1059

LOGFILE=`mktemp -t svn_checkout.XXXXXX`
ICONPATH="`dirname $0`/svn.xpm"

URL=`zenity --entry --title="Subversion: Checkout" --text="Enter repository URL:" --entry-text="svn://" --width=400 --window-icon="$ICONPATH" 2>&1`

if [ $? -eq 0 ] ; then
    svn checkout $URL &> $LOGFILE
    zenity --text-info --title="Subversion: Checkout" --filename=$LOGFILE --width=600 --height=400 --window-icon="$ICONPATH"
    rm -f $LOGFILE
fi
