#!/bin/bash
#
# Distributed under the terms of GNU GPL version 2
#
# James Morgan
# http://morgan-design.com


LOGFILE=`mktemp -t svn_update.XXXXXX`

svn propget svn:externals -R "$@" > $LOGFILE
zenity --text-info --title="Subversion: Externals" --filename=$LOGFILE --width=600 --height=400 --window-icon="`dirname $0`/svn.xpm"
rm -f $LOGFILE
