#!/bin/sh
set -e

for i in `find ./ -maxdepth 1 -mindepth 1 -type d ! -name ".*"`; do
   cd $i
   echo     ....
   echo     ....
   echo     ........................................... BUILDING: $i
   echo     ....
   echo     ....
   sudo mk-build-deps -ir
   dpkg-buildpackage -us -uc -j$((    $(cat /proc/cpuinfo | grep processor | wc -l)+1    ))
   cd ..
done
