#!/bin/sh

for i in `find ./ -maxdepth 1 -mindepth 1 -type d`; do
   if [ $i = "./.git" ]; then
      continue
   fi
   cd $i
   echo     ....
   echo     ....
   echo     ........................................... BUILDING: $i
   echo     ....
   echo     ....
   dpkg-buildpackage -j$((    $(cat /proc/cpuinfo | grep processor | wc -l)+1    ))
   cd ..
done
