.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH NEMO-COMPARE-PREFERENCES 1 "October 29, 2011"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
nemo-compare-preferences \- Nemo Compare preferences dialog
.SH SYNOPSIS
.B nemo-compare-preferences
.SH DESCRIPTION
.B 'nemo-compare-preferences' is a graphical tool to set preferences for
.B Nemo Compare
which is a small extension for the Nemo file manager, which allows users
to compare selected files from the context menu as well as remember them for
later comparison.
.PP
.B nemo-compare-preferences
has been written in Python and GTK+, and after installing the application you
can run it from the application launcher.
.SH SEE ALSO
.BR nemo (1)
.br
.SH AUTHOR
.nh
nemo-compare-preferences was written by Guido Tabbernuk
<boamaod@gmail.com>.
.PP
This manual page was written by Guido Tabbernuk <boamaod@gmail.com>,
for the Debian project (and may be used by others).
