#!/bin/sh
# postinst script for nemo-compare
#
# see: dh_installdeb(1)

set -e

unud=/var/lib/update-notifier/user.d

if [ -d $unud ]; then
	cp /usr/share/nemo-compare/nemo-compare-notification \
		/var/lib/update-notifier/user.d/
	touch /var/lib/update-notifier/dpkg-run-stamp
fi

#DEBHELPER#
