#!/bin/sh
#
# Distributed under the terms of GNU GPL version 2
#

if [ -r "`dirname "$0"`/git.conf" ]; then
  . "`dirname "$0"`/git.conf"
elif [ -r "`dirname "$0"`/../git.conf" ]; then
  . "`dirname "$0"`/../git.conf"
else
  exit 1
fi

if [ -f "$@" ]; then
  $GIT $GIT_OPTS blame "$@" 1>> "$OUTPUT" 2>> "$OUTPUT"
  _zenity_info "$?" "Unknown" "Unknown error (more information can be found at ~/.xsession-errors)"
else
  _zenity_error_text "Please select a single file and try again ..."
fi

